// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package eset

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "eset", asset.ModuleFieldsPri, AssetEset); err != nil {
		panic(err)
	}
}

// AssetEset returns asset data.
// This is the base64 encoded gzipped contents of module/eset.
func AssetEset() string {
	return "eJwEwLENgzAQheHeU/wLZAEXaRAlFVkAwQOdYuzIdyCxfb4XXz0ZuSJBWBRlxnn8MGu9usXDtNTl0KkaDKqhnmCTr91+Ya1m3glgattVRDS6VtktSjucvbeTcZ4Gblvwx0s7EuymsnlO/wAAAP//noYqQg=="
}
